export type OnyomiExample = {
  id: string
  rhyme: string
  pinyin: string
  kanji: string
  onyomi: string
  japaneseWords: string[]
}

export const ONYOMI_EXAMPLES: OnyomiExample[] = [
  {
    id: 'uang-wang-王',
    rhyme: 'uang',
    pinyin: 'wang',
    kanji: '王',
    onyomi: 'おう',
    japaneseWords: ['王国', '王子'],
  },
  {
    id: 'uang-wang-望',
    rhyme: 'uang',
    pinyin: 'wang',
    kanji: '望',
    onyomi: 'ぼう',
    japaneseWords: ['希望', '願望'],
  },
  {
    id: 'ang-bang-棒',
    rhyme: 'ang',
    pinyin: 'bang',
    kanji: '棒',
    onyomi: 'ぼう',
    japaneseWords: ['鉄棒', '泥棒'],
  },
  {
    id: 'ang-guang-光',
    rhyme: 'ang',
    pinyin: 'guang',
    kanji: '光',
    onyomi: 'こう',
    japaneseWords: ['光線', '観光'],
  },
  {
    id: 'ang-huang-黄',
    rhyme: 'ang',
    pinyin: 'huang',
    kanji: '黄',
    onyomi: 'こう',
    japaneseWords: ['黄金', '黄色'],
  },
  {
    id: 'ang-fang-方',
    rhyme: 'ang',
    pinyin: 'fang',
    kanji: '方',
    onyomi: 'ほう',
    japaneseWords: ['方向', '方法'],
  },
  {
    id: 'ang-fang-訪',
    rhyme: 'ang',
    pinyin: 'fang',
    kanji: '訪',
    onyomi: 'ほう',
    japaneseWords: ['訪問'],
  },
  {
    id: 'ang-fang-防',
    rhyme: 'ang',
    pinyin: 'fang',
    kanji: '防',
    onyomi: 'ぼう',
    japaneseWords: ['防止', '消防'],
  },
  {
    id: 'ang-chang-長',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '長',
    onyomi: 'ちょう',
    japaneseWords: ['長期', '成長'],
  },
  {
    id: 'ang-chang-腸',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '腸',
    onyomi: 'ちょう',
    japaneseWords: ['胃腸'],
  },
  {
    id: 'ang-chang-商',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '商',
    onyomi: 'しょう',
    japaneseWords: ['商品', '商店'],
  },
  {
    id: 'ang-chang-賞',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '賞',
    onyomi: 'しょう',
    japaneseWords: ['受賞', '賞品'],
  },
  {
    id: 'ang-chang-障',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '障',
    onyomi: 'しょう',
    japaneseWords: ['障害'],
  },
  {
    id: 'ang-chang-場',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '場',
    onyomi: 'じょう',
    japaneseWords: ['会場', '登場'],
  },
  {
    id: 'ang-chang-常',
    rhyme: 'ang',
    pinyin: 'chang',
    kanji: '常',
    onyomi: 'じょう',
    japaneseWords: ['正常', '日常'],
  },
  {
    id: 'ang-rang-譲',
    rhyme: 'ang',
    pinyin: 'rang',
    kanji: '譲',
    onyomi: 'じょう',
    japaneseWords: ['譲渡'],
  },
  {
    id: 'ang-rang-壌',
    rhyme: 'ang',
    pinyin: 'rang',
    kanji: '壌',
    onyomi: 'じょう',
    japaneseWords: ['土壌'],
  },
]

export const ONYOMI_ALL_RHYMES = [
  'a',
  'o',
  'e',
  'i',
  'u',
  'ü',
  'ai',
  'ei',
  'ui',
  'ao',
  'ou',
  'iu',
  'ie',
  'üe',
  'er',
  'an',
  'en',
  'in',
  'un',
  'ün',
  'ang',
  'eng',
  'ing',
  'ong',
  'ia',
  'ua',
  'uo',
  'iao',
  'ian',
  'uang',
  'iong',
] as const

export const ONYOMI_RHYMES = ['all', 'ang', 'uang'] as const
export const ONYOMI_MODES = ['mode1', 'mode2'] as const
