import type { OnyomiRhymeDataset } from '../types'

export const angDataset: OnyomiRhymeDataset = {
  key: 'ang',
  label: 'ang',
  examples: [
    {
      id: 'ang-bang-棒',
      rhyme: 'ang',
      pinyin: 'bang',
      kanji: '棒',
      onyomi: 'ぼう',
      japaneseWords: ['棒（ぼう）'],
    },
    {
      id: 'ang-cang-蔵',
      rhyme: 'ang',
      pinyin: 'cang',
      kanji: '蔵',
      onyomi: 'ぞう',
      japaneseWords: ['冷蔵庫（れいぞうこ）'],
    },
    {
      id: 'ang-dang-当',
      rhyme: 'ang',
      pinyin: 'dang',
      kanji: '当',
      onyomi: 'とう',
      japaneseWords: [
        '本当（ほんとう）',
        '当時（とうじ）',
        '当然（とうぜん）',
        '当選する（とうせんする）',
        '適当だ（てきとうだ）',
        '担当（たんとう）',
        '当〜（とう〜）',
        '当日（とうじつ）',
        '弁当（べんとう）',
        '見当（けんとう）',
        '相当する（そうとうする）',
        '相当（そうとう）',
      ],
    },
    {
      id: 'ang-fang-方',
      rhyme: 'ang',
      pinyin: 'fang',
      kanji: '方',
      onyomi: 'ほう',
      japaneseWords: [
        '方法（ほうほう）',
        '地方（ちほう）',
        '方言（ほうげん）',
        '方面（ほうめん）',
        '一方で（いっぽうで）',
        '両方（りょうほう）',
        '平方（へいほう）',
        '漢方薬（かんぽうやく）',
        '前方（ぜんぽう）',
      ],
    },
    {
      id: 'ang-fang-訪',
      rhyme: 'ang',
      pinyin: 'fang',
      kanji: '訪',
      onyomi: 'ほう',
      japaneseWords: ['訪日（ほうにち）', '訪問する（ほうもんする）', '訪問中（ほうもんちゅう）'],
    },
    {
      id: 'ang-fang-放',
      rhyme: 'ang',
      pinyin: 'fang',
      kanji: '放',
      onyomi: 'ほう',
      japaneseWords: ['放送する（ほうそうする）', '放射線（ほうしゃせん）', '追放（ついほう）'],
    },
    {
      id: 'ang-fang-防',
      rhyme: 'ang',
      pinyin: 'fang',
      kanji: '防',
      onyomi: 'ぼう',
      japaneseWords: ['消防士（しょうぼうし）', '防腐（ぼうふ）', '防水（ぼうすい）', '防寒服（ぼうかんふく）', '予防（よぼう）'],
    },
    {
      id: 'ang-fang-房',
      rhyme: 'ang',
      pinyin: 'fang',
      kanji: '房',
      onyomi: 'ぼう',
      japaneseWords: ['文房具（ぶんぼうぐ）'],
    },
    {
      id: 'ang-gang-鋼',
      rhyme: 'ang',
      pinyin: 'gang',
      kanji: '鋼',
      onyomi: 'こう',
      japaneseWords: ['鉄鋼（てっこう）'],
    },
    {
      id: 'ang-gang-港',
      rhyme: 'ang',
      pinyin: 'gang',
      kanji: '港',
      onyomi: 'こう',
      japaneseWords: ['空港（くうこう）'],
    },
    {
      id: 'ang-hang-航',
      rhyme: 'ang',
      pinyin: 'hang',
      kanji: '航',
      onyomi: 'こう',
      japaneseWords: ['航空便（こうくうびん）', '航海士（こうかいし）', '航空（こうくう）', '航海（こうかい）', '航海する（こうかいする）'],
    },
    {
      id: 'ang-kang-康',
      rhyme: 'ang',
      pinyin: 'kang',
      kanji: '康',
      onyomi: 'こう',
      japaneseWords: ['健康（けんこう）'],
    },
    {
      id: 'ang-kang-抗',
      rhyme: 'ang',
      pinyin: 'kang',
      kanji: '抗',
      onyomi: 'こう',
      japaneseWords: ['抗議（こうぎ）'],
    },
    {
      id: 'ang-lang-廊',
      rhyme: 'ang',
      pinyin: 'lang',
      kanji: '廊',
      onyomi: 'ろう',
      japaneseWords: ['廊下（ろうか）'],
    },
    {
      id: 'ang-mang-忙',
      rhyme: 'ang',
      pinyin: 'mang',
      kanji: '忙',
      onyomi: 'ぼう',
      japaneseWords: ['多忙（たぼう）'],
    },
    {
      id: 'ang-tang-湯',
      rhyme: 'ang',
      pinyin: 'tang',
      kanji: '湯',
      onyomi: 'とう',
      japaneseWords: ['湯治（とうじ）'],
    },
    {
      id: 'ang-tang-糖',
      rhyme: 'ang',
      pinyin: 'tang',
      kanji: '糖',
      onyomi: 'とう',
      japaneseWords: ['砂糖（さとう）', '糖尿病（とうにょうびょう）'],
    },
    {
      id: 'ang-tang-堂',
      rhyme: 'ang',
      pinyin: 'tang',
      kanji: '堂',
      onyomi: 'どう',
      japaneseWords: ['食堂（しょくどう）', '講堂（こうどう）'],
    },
    {
      id: 'ang-zang-臓',
      rhyme: 'ang',
      pinyin: 'zang',
      kanji: '臓',
      onyomi: 'ぞう',
      japaneseWords: ['心臓（しんぞう）'],
    },
    {
      id: 'ang-chang-長',
      rhyme: 'ang',
      pinyin: 'chang',
      kanji: '長',
      onyomi: 'ちょう',
      japaneseWords: [
        '長安（ちょうあん）',
        '長所（ちょうしょ）',
        '成長する（せいちょうする）',
        '部長（ぶちょう）',
        '身長（しんちょう）',
        '課長（かちょう）',
        '社長（しゃちょう）',
        '団長（だんちょう）',
        '長時間（ちょうじかん）',
        '生長（せいちょう）',
      ],
    },
    {
      id: 'ang-chang-腸',
      rhyme: 'ang',
      pinyin: 'chang',
      kanji: '腸',
      onyomi: 'ちょう',
      japaneseWords: ['大腸菌（だいちょうきん）'],
    },
    {
      id: 'ang-chang-償',
      rhyme: 'ang',
      pinyin: 'chang',
      kanji: '償',
      onyomi: 'しょう',
      japaneseWords: ['弁償する（べんしょうする）', '無償（むしょう）'],
    },
    {
      id: 'ang-chang-場',
      rhyme: 'ang',
      pinyin: 'chang',
      kanji: '場',
      onyomi: 'じょう',
      japaneseWords: ['工場（こうじょう）', '劇場（げきじょう）', '展示場（てんじじょう）', '登場する（とうじょうする）', '会場（かいじょう）', '飛行場（ひこうじょう）'],
    },
    {
      id: 'ang-chang-常',
      rhyme: 'ang',
      pinyin: 'chang',
      kanji: '常',
      onyomi: 'じょう',
      japaneseWords: ['日常（にちじょう）', '日常茶飯事（にちじょうさはんじ）', '常識（じょうしき）'],
    },
    {
      id: 'ang-shang-商',
      rhyme: 'ang',
      pinyin: 'shang',
      kanji: '商',
      onyomi: 'しょう',
      japaneseWords: ['商品（しょうひん）', '商店（しょうてん）', '商店街（しょうてんがい）'],
    },
    {
      id: 'ang-shang-傷',
      rhyme: 'ang',
      pinyin: 'shang',
      kanji: '傷',
      onyomi: 'しょう',
      japaneseWords: ['凍傷（とうしょう）', '重傷（じゅうしょう）', '軽傷（けいしょう）'],
    },
    {
      id: 'ang-shang-賞',
      rhyme: 'ang',
      pinyin: 'shang',
      kanji: '賞',
      onyomi: 'しょう',
      japaneseWords: ['鑑賞（かんしょう）', '入賞する（にゅうしょうする）'],
    },
    {
      id: 'ang-shang-上',
      rhyme: 'ang',
      pinyin: 'shang',
      kanji: '上',
      onyomi: 'じょう',
      japaneseWords: [
        '上手だ（じょうずだ）',
        '頂上（ちょうじょう）',
        '以上（いじょう）',
        '向上する（こうじょうする）',
        '上達する（じょうたつする）',
        '地球上（ちきゅうじょう）',
        '上昇幅（じょうしょうはば）',
        '最上（さいじょう）',
        '路上（ろじょう）',
      ],
    },
    {
      id: 'ang-zhang-章',
      rhyme: 'ang',
      pinyin: 'zhang',
      kanji: '章',
      onyomi: 'しょう',
      japaneseWords: ['文章（ぶんしょう）'],
    },
    {
      id: 'ang-zhang-障',
      rhyme: 'ang',
      pinyin: 'zhang',
      kanji: '障',
      onyomi: 'しょう',
      japaneseWords: ['故障（こしょう）', '障子（しょうじ）', '保障（ほしょう）'],
    },
    {
      id: 'ang-zhang-丈',
      rhyme: 'ang',
      pinyin: 'zhang',
      kanji: '丈',
      onyomi: 'じょう',
      japaneseWords: ['丈夫（じょうぶ）', '大丈夫（だいじょうぶ）', '頑丈だ（がんじょうだ）'],
    },
    {
      id: 'ang-zhang-張',
      rhyme: 'ang',
      pinyin: 'zhang',
      kanji: '張',
      onyomi: 'ちょう',
      japaneseWords: ['張（ちょう）', '出張する（しゅっちょうする）', '緊張する（きんちょうする）'],
    },
    {
      id: 'ang-zhang-帳',
      rhyme: 'ang',
      pinyin: 'zhang',
      kanji: '帳',
      onyomi: 'ちょう',
      japaneseWords: ['手帳（てちょう）'],
    },
    {
      id: 'ang-rang-壌',
      rhyme: 'ang',
      pinyin: 'rang',
      kanji: '壌',
      onyomi: 'じょう',
      japaneseWords: ['土壌（どじょう）'],
    },
    {
      id: 'ang-rang-譲',
      rhyme: 'ang',
      pinyin: 'rang',
      kanji: '譲',
      onyomi: 'じょう',
      japaneseWords: ['分譲（ぶんじょう）'],
    },
  ],
}
