import type { OnyomiRhymeDataset } from '../types'

export const engDataset: OnyomiRhymeDataset = {
  key: 'eng',
  label: 'eng',
  examples: [
    {
      id: 'eng-beng-崩',
      rhyme: 'eng',
      pinyin: 'beng',
      kanji: '崩',
      onyomi: 'ほう',
      japaneseWords: ['崩壊（ほうかい）'],
    },
    {
      id: 'eng-ceng-層',
      rhyme: 'eng',
      pinyin: 'ceng',
      kanji: '層',
      onyomi: 'そう',
      japaneseWords: ['一層（いっそう）', '高層（こうそう）', '地層（ちそう）'],
    },
    {
      id: 'eng-deng-登1',
      rhyme: 'eng',
      pinyin: 'deng',
      kanji: '登',
      onyomi: 'とう',
      japaneseWords: ['登場する（とうじょうする）'],
    },
    {
      id: 'eng-deng-等',
      rhyme: 'eng',
      pinyin: 'deng',
      kanji: '等',
      onyomi: 'どう',
      japaneseWords: ['平等（びょうどう）'],
    },
    {
      id: 'eng-feng-縫',
      rhyme: 'eng',
      pinyin: 'feng',
      kanji: '縫',
      onyomi: 'ほう',
      japaneseWords: ['裁縫（さいほう）'],
    },
    {
      id: 'eng-geng-耕',
      rhyme: 'eng',
      pinyin: 'geng',
      kanji: '耕',
      onyomi: 'こう',
      japaneseWords: ['耕運機（こううんき）'],
    },
    {
      id: 'eng-feng-豊',
      rhyme: 'eng',
      pinyin: 'feng',
      kanji: '豊',
      onyomi: 'ほう',
      japaneseWords: ['豊富だ（ほうふだ）', '豊作（ほうさく）'],
    },
    {
      id: 'eng-neng-能',
      rhyme: 'eng',
      pinyin: 'neng',
      kanji: '能',
      onyomi: 'のう',
      japaneseWords: ['芸能（げいのう）', '性能（せいのう）', '技能（ぎのう）', '能率（のうりつ）', '才能（さいのう）', '機能（きのう）', '可能性（かのうせい）', '不可能だ（ふかのうだ）', '能力（のうりょく）', '可能だ（かのうだ）'],
    },
    {
      id: 'eng-peng-膨',
      rhyme: 'eng',
      pinyin: 'peng',
      kanji: '膨',
      onyomi: 'ぼう',
      japaneseWords: ['膨大だ（ぼうだいだ）'],
    },
    {
      id: 'eng-zeng-増',
      rhyme: 'eng',
      pinyin: 'zeng',
      kanji: '増',
      onyomi: 'ぞう',
      japaneseWords: ['増加する（ぞうかする）'],
    },
    {
      id: 'eng-zeng-贈',
      rhyme: 'eng',
      pinyin: 'zeng',
      kanji: '贈',
      onyomi: 'ぞう',
      japaneseWords: ['贈答品（ぞうとうひん）'],
    },
    {
      id: 'eng-cheng-成',
      rhyme: 'eng',
      pinyin: 'cheng',
      kanji: '成',
      onyomi: 'せい',
      japaneseWords: ['成功する（せいこうする）', '成長する（せいちょうする）', '成語（せいご）', '促成（そくせい）', '成績（せいせき）', '賛成（さんせい）', '完成する（かんせいする）', '成分（せいぶん）', '合成する（ごうせいする）'],
    },
    {
      id: 'eng-cheng-誠',
      rhyme: 'eng',
      pinyin: 'cheng',
      kanji: '誠',
      onyomi: 'せい',
      japaneseWords: ['誠実だ（せいじつだ）'],
    },
    {
      id: 'eng-cheng-程',
      rhyme: 'eng',
      pinyin: 'cheng',
      kanji: '程',
      onyomi: 'てい',
      japaneseWords: ['日程（にってい）', '程度（ていど）', '過程（かてい）'],
    },
    {
      id: 'eng-sheng-生1',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '生',
      onyomi: 'せい',
      japaneseWords: ['生活（せいかつ）', '学生（がくせい）', '先生（せんせい）', '留学生（りゅうがくせい）', '小学生（しょうがくせい）', '研修生（けんしゅうせい）', '生産（せいさん）', '生命（せいめい）', '生徒（せいと）', '一生懸命（いっしょうけんめい）', '学生服（がくせいふく）', '人生（じんせい）', '高校生（こうこうせい）', '生物（せいぶつ）', '生長（せいちょう）', '大量生産（たいりょうせいさん）', '生還（せいかん）', '国民総生産（こくみんそうせいさん）', '微生物（びせいぶつ）', '食生活（しょくせいかつ）'],
    },
    {
      id: 'eng-sheng-声',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '声',
      onyomi: 'せい',
      japaneseWords: ['声調（せいちょう）', '四声（しせい）'],
    },
    {
      id: 'eng-sheng-省1',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '省',
      onyomi: 'せい',
      japaneseWords: ['帰省する（きせいする）'],
    },
    {
      id: 'eng-sheng-盛',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '盛',
      onyomi: 'せい',
      japaneseWords: ['盛夏（せいか）'],
    },
    {
      id: 'eng-zheng-整',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '整',
      onyomi: 'せい',
      japaneseWords: ['整備する（せいびする）'],
    },
    {
      id: 'eng-zheng-正1',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '正',
      onyomi: 'せい',
      japaneseWords: ['正確だ（せいかくだ）', '修正する（しゅうせいする）', '不正（ふせい）'],
    },
    {
      id: 'eng-cheng-承',
      rhyme: 'eng',
      pinyin: 'cheng',
      kanji: '承',
      onyomi: 'しょう',
      japaneseWords: ['承認する（しょうにんする）'],
    },
    {
      id: 'eng-cheng-乗',
      rhyme: 'eng',
      pinyin: 'cheng',
      kanji: '乗',
      onyomi: 'じょう',
      japaneseWords: ['乗車券（じょうしゃけん）'],
    },
    {
      id: 'eng-sheng-生2',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '生',
      onyomi: 'しょう',
      japaneseWords: ['誕生日（たんじょうび）', '生涯（しょうがい）', '一生（いっしょう）', '誕生する（たんじょうする）'],
    },
    {
      id: 'eng-sheng-省2',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '省',
      onyomi: 'しょう',
      japaneseWords: ['四川省（しせんしょう）', '山西省（さんせいしょう）'],
    },
    {
      id: 'eng-sheng-昇',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '昇',
      onyomi: 'しょう',
      japaneseWords: ['昇進（しょうしん）', '上昇幅（じょうしょうはば）'],
    },
    {
      id: 'eng-sheng-勝',
      rhyme: 'eng',
      pinyin: 'sheng',
      kanji: '勝',
      onyomi: 'しょう',
      japaneseWords: ['健勝（けんしょう）', '優勝する（ゆうしょうする）'],
    },
    {
      id: 'eng-zheng-正2',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '正',
      onyomi: 'しょう',
      japaneseWords: ['正月（しょうがつ）', '正直だ（しょうじきだ）', '大正（たいしょう）'],
    },
    {
      id: 'eng-zheng-証',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '証',
      onyomi: 'しょう',
      japaneseWords: ['証明する（しょうめいする）', '証拠（しょうこ）', '保証（ほしょう）'],
    },
    {
      id: 'eng-zheng-蒸',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '蒸',
      onyomi: 'じょう',
      japaneseWords: ['水蒸気（すいじょうき）'],
    },
    {
      id: 'eng-zheng-徴',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '徴',
      onyomi: 'ちょう',
      japaneseWords: ['特徴（とくちょう）'],
    },
    {
      id: 'eng-zheng-争',
      rhyme: 'eng',
      pinyin: 'zheng',
      kanji: '争',
      onyomi: 'そう',
      isSpecial: true,
      japaneseWords: ['競争（きょうそう）'],
    },
    {
      id: 'eng-leng-冷',
      rhyme: 'eng',
      pinyin: 'leng',
      kanji: '冷',
      onyomi: 'れい',
      isSpecial: true,
      japaneseWords: ['冷蔵庫（れいぞうこ）', '冷凍（れいとう）'],
    },
    {
      id: 'eng-feng-風1',
      rhyme: 'eng',
      pinyin: 'feng',
      kanji: '風',
      onyomi: 'ふう',
      isSpecial: true,
      japaneseWords: ['風物（ふうぶつ）', '台風（たいふう）', '扇風機（せんぷうき）', '風土（ふうど）', '風景（ふうけい）', '風雨（ふうう）', '欧米風（おうべいふう）', '風（ふう）', '風味（ふうみ）', '微風（びふう）', '風船（ふうせん）'],
    },
    {
      id: 'eng-feng-風2',
      rhyme: 'eng',
      pinyin: 'feng',
      kanji: '風',
      onyomi: 'ふ',
      isSpecial: true,
      japaneseWords: ['風呂（ふろ）'],
    },
    {
      id: 'eng-feng-封',
      rhyme: 'eng',
      pinyin: 'feng',
      kanji: '封',
      onyomi: 'ふう',
      isSpecial: true,
      japaneseWords: ['封筒（ふうとう）', '密封する（みっぷうする）', '同封（どうふう）'],
    },
    {
      id: 'eng-deng-登2',
      rhyme: 'eng',
      pinyin: 'deng',
      kanji: '登',
      onyomi: 'と',
      isSpecial: true,
      japaneseWords: ['登山（とざん）', '登山家（とざんか）', '登頂（とちょう）'],
    },
  ],
}
