import type { OnyomiRhymeDataset } from '../types'

export const iangDataset: OnyomiRhymeDataset = {
  key: 'iang',
  label: 'iang',
  examples: [
    {
      id: 'iang-jiang-将',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '将',
      onyomi: 'しょう',
      japaneseWords: ['将来（しょうらい）', '将棋（しょうぎ）'],
    },
    {
      id: 'iang-jiang-奨',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '奨',
      onyomi: 'しょう',
      japaneseWords: ['奨励する（しょうれいする）'],
    },
    {
      id: 'iang-jiang-醤',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '醤',
      onyomi: 'しょう',
      japaneseWords: ['醤油（しょうゆ）'],
    },
    {
      id: 'iang-liang-良',
      rhyme: 'iang',
      pinyin: 'liang',
      kanji: '良',
      onyomi: 'りょう',
      japaneseWords: ['不良品（ふりょうひん）', '改良する（かいりょうする）'],
    },
    {
      id: 'iang-liang-糧',
      rhyme: 'iang',
      pinyin: 'liang',
      kanji: '糧',
      onyomi: 'りょう',
      japaneseWords: ['食糧（しょくりょう）'],
    },
    {
      id: 'iang-liang-両',
      rhyme: 'iang',
      pinyin: 'liang',
      kanji: '両',
      onyomi: 'りょう',
      japaneseWords: ['両国（りょうごく）', '両立（りょうりつ）', '両親（りょうしん）', '両方（りょうほう）'],
    },
    {
      id: 'iang-liang-量',
      rhyme: 'iang',
      pinyin: 'liang',
      kanji: '量',
      onyomi: 'りょう',
      japaneseWords: ['交通量（こうつうりょう）', '量（りょう）', '少量（しょうりょう）', '同量（どうりょう）', '大量（たいりょう）', '降水量（こうすいりょう）'],
    },
    {
      id: 'iang-niang-娘',
      rhyme: 'iang',
      pinyin: 'niang',
      kanji: '娘',
      onyomi: 'じょう',
      japaneseWords: ['お嬢さん（おじょうさん）'],
    },
    {
      id: 'iang-qiang-強',
      rhyme: 'iang',
      pinyin: 'qiang',
      kanji: '強',
      onyomi: 'きょう',
      japaneseWords: ['勉強（べんきょう）', '補強材（ほきょうざい）'],
    },
    {
      id: 'iang-xiang-相2',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '相',
      onyomi: 'しょう',
      japaneseWords: ['首相（しゅしょう）'],
    },
    {
      id: 'iang-xiang-郷1',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '郷',
      onyomi: 'きょう',
      japaneseWords: ['故郷（こきょう）'],
    },
    {
      id: 'iang-xiang-祥',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '祥',
      onyomi: 'しょう',
      japaneseWords: ['吉祥寺（きちじょうじ）'],
    },
    {
      id: 'iang-xiang-響',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '響',
      onyomi: 'きょう',
      japaneseWords: ['影響（えいきょう）'],
    },
    {
      id: 'iang-xiang-象',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '象',
      onyomi: 'しょう',
      japaneseWords: ['抽象的だ（ちゅうしょうてきだ）', '気象（きしょう）', '気象庁（きしょうちょう）', '印象（いんしょう）', '気象学者（きしょうがくしゃ）', '現象（げんしょう）'],
    },
    {
      id: 'iang-yang-洋',
      rhyme: 'iang',
      pinyin: 'yang',
      kanji: '洋',
      onyomi: 'よう',
      japaneseWords: ['洋服（ようふく）', '洋装店（ようそうてん）', '洋室（ようしつ）', '西洋（せいよう）', '大西洋（たいせいよう）', '太平洋（たいへいよう）'],
    },
    {
      id: 'iang-yang-陽',
      rhyme: 'iang',
      pinyin: 'yang',
      kanji: '陽',
      onyomi: 'よう',
      japaneseWords: ['太陽（たいよう）', '陽気だ（ようきだ）', '陽春（ようしゅん）'],
    },
    {
      id: 'iang-yang-揚',
      rhyme: 'iang',
      pinyin: 'yang',
      kanji: '揚',
      onyomi: 'よう',
      japaneseWords: ['揚子江（ようすこう）'],
    },
    {
      id: 'iang-yang-養',
      rhyme: 'iang',
      pinyin: 'yang',
      kanji: '養',
      onyomi: 'よう',
      japaneseWords: ['休養（きゅうよう）', '栄養（えいよう）', '扶養する（ふようする）', '栄養分（えいようぶん）', '教養（きょうよう）'],
    },
    {
      id: 'iang-yang-様',
      rhyme: 'iang',
      pinyin: 'yang',
      kanji: '様',
      onyomi: 'よう',
      japaneseWords: ['様子（ようす）', '異様だ（いようだ）', '多種多様（たしゅたよう）'],
    },
    {
      id: 'iang-jiang-江',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '江',
      onyomi: 'こう',
      japaneseWords: ['揚子江（ようすこう）'],
    },
    {
      id: 'iang-jiang-講',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '講',
      onyomi: 'こう',
      japaneseWords: ['講座（こうざ）', '講義（こうぎ）', '休講（きゅうこう）', '講演（こうえん）', '講演会（こうえんかい）', '講堂（こうどう）'],
    },
    {
      id: 'iang-jiang-降',
      rhyme: 'iang',
      pinyin: 'jiang',
      kanji: '降',
      onyomi: 'こう',
      japaneseWords: ['降水量（こうすいりょう）'],
    },
    {
      id: 'iang-xiang-相1',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '相',
      onyomi: 'そう',
      japaneseWords: ['相談する（そうだんする）', '相談（そうだん）', '相当する（そうとうする）', '相当（そうとう）'],
    },
    {
      id: 'iang-xiang-想',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '想',
      onyomi: 'そう',
      japaneseWords: ['感想（かんそう）', '想像する（そうぞうする）', '予想（よそう）', '幻想的だ（げんそうてきだ）', '思想（しそう）', '理想（りそう）', '発想（はっそう）', '理想的だ（りそうてきだ）'],
    },
    {
      id: 'iang-xiang-像',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '像',
      onyomi: 'ぞう',
      japaneseWords: ['映像（えいぞう）', '想像する（そうぞうする）'],
    },
    {
      id: 'iang-xiang-向',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '向',
      onyomi: 'こう',
      japaneseWords: ['向上する（こうじょうする）', '傾向（けいこう）', '一向に（いっこうに）'],
    },
    {
      id: 'iang-xiang-郷2',
      rhyme: 'iang',
      pinyin: 'xiang',
      kanji: '郷',
      onyomi: 'ごう',
      japaneseWords: ['水郷（すいごう）', '近郷（きんごう）','郷里制（ごうりせい）','郷に入っては郷に従え（ごうにいってはごうにしたがえ）'],
    },
  ],
}
