import type { OnyomiRhymeDataset } from '../types'

export const ingDataset: OnyomiRhymeDataset = {
  key: 'ing',
  label: 'ing',
  examples: [
    {
      id: 'ing-ying-英',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '英',
      onyomi: 'えい',
      japaneseWords: ['英語（えいご）'],
    },
    {
      id: 'ing-ying-営',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '営',
      onyomi: 'えい',
      japaneseWords: ['営業部（えいぎょうぶ）', '野営する（やえいする）'],
    },
    {
      id: 'ing-ying-影',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '影',
      onyomi: 'えい',
      japaneseWords: ['影響（えいきょう）', '撮影（さつえい）'],
    },
    {
      id: 'ing-ying-映',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '映',
      onyomi: 'えい',
      japaneseWords: ['映画（えいが）', '映像（えいぞう）'],
    },
    {
      id: 'ing-jing-経',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '経',
      onyomi: 'けい',
      japaneseWords: ['経済（けいざい）', '経験（けいけん）', '経理部（けいりぶ）', '経済力（けいざいりょく）', '経過（けいか）'],
    },
    {
      id: 'ing-jing-景1',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '景',
      onyomi: 'けい',
      japaneseWords: ['光景（こうけい）', '風景（ふうけい）', '景観（けいかん）'],
    },
    {
      id: 'ing-jing-警',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '警',
      onyomi: 'けい',
      japaneseWords: ['警察官（けいさつかん）', '警察（けいさつ）'],
    },
    {
      id: 'ing-jing-敬',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '敬',
      onyomi: 'けい',
      japaneseWords: ['敬語（けいご）', '敬意（けいい）', '尊敬する（そんけいする）', '敬具（けいぐ）', '敬遠する（けいえんする）'],
    },
    {
      id: 'ing-qing-軽',
      rhyme: 'ing',
      pinyin: 'qing',
      kanji: '軽',
      onyomi: 'けい',
      japaneseWords: ['軽傷（けいしょう）'],
    },
    {
      id: 'ing-qing-傾',
      rhyme: 'ing',
      pinyin: 'qing',
      kanji: '傾',
      onyomi: 'けい',
      japaneseWords: ['傾向（けいこう）'],
    },
    {
      id: 'ing-xing-形',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '形',
      onyomi: 'けい',
      japaneseWords: ['形式（けいしき）', '地形（ちけい）'],
    },
    {
      id: 'ing-ying-迎',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '迎',
      onyomi: 'げい',
      japaneseWords: ['歓迎（かんげい）'],
    },
    {
      id: 'ing-jing-精',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '精',
      onyomi: 'せい',
      japaneseWords: ['精密だ（せいみつだ）', '精度（せいど）', '精いっぱい（せいいっぱい）', '精製する（せいせいする）', '精々（せいぜい）'],
    },
    {
      id: 'ing-qing-清',
      rhyme: 'ing',
      pinyin: 'qing',
      kanji: '清',
      onyomi: 'せい',
      japaneseWords: ['清潔だ（せいけつだ）', '清栄（せいえい）'],
    },
    {
      id: 'ing-xing-星',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '星',
      onyomi: 'せい',
      japaneseWords: ['衛星（えいせい）'],
    },
    {
      id: 'ing-xing-性',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '性',
      onyomi: 'せい',
      japaneseWords: [
        '性能（せいのう）',
        '女性（じょせい）',
        '個性（こせい）',
        '男性（だんせい）',
        '性格（せいかく）',
        '性質（せいしつ）',
        '植物性（しょくぶつせい）',
        '可能性（かのうせい）',
        '主体性（しゅたいせい）',
        '習性（しゅうせい）',
        '活性炭（かっせいたん）',
        '特性（とくせい）',
        '安全性（あんぜんせい）',
        '必要性（ひつようせい）',
      ],
    },
    {
      id: 'ing-ding-丁2',
      rhyme: 'ing',
      pinyin: 'ding',
      kanji: '丁',
      onyomi: 'てい',
      japaneseWords: ['丁寧だ（ていねいだ）'],
    },
    {
      id: 'ing-ding-定',
      rhyme: 'ing',
      pinyin: 'ding',
      kanji: '定',
      onyomi: 'てい',
      japaneseWords: ['定着する（ていちゃくする）', '予定（よてい）', '定着する（固定）（ていちゃくする）', '指定席（していせき）', '規定する（きていする）', '定義する（ていぎする）', '設定する（せっていする）', '眼底（がんてい）', '肯定（こうてい）'],
    },
    {
      id: 'ing-ting-庭',
      rhyme: 'ing',
      pinyin: 'ting',
      kanji: '庭',
      onyomi: 'てい',
      japaneseWords: ['庭園（ていえん）', '家庭科（かていか）'],
    },
    {
      id: 'ing-ting-停',
      rhyme: 'ing',
      pinyin: 'ting',
      kanji: '停',
      onyomi: 'てい',
      japaneseWords: ['停車場（ていしゃば）'],
    },
    {
      id: 'ing-ning-寧',
      rhyme: 'ing',
      pinyin: 'ning',
      kanji: '寧',
      onyomi: 'ねい',
      japaneseWords: ['丁寧だ（ていねいだ）'],
    },
    {
      id: 'ing-ping-平1',
      rhyme: 'ing',
      pinyin: 'ping',
      kanji: '平',
      onyomi: 'へい',
      japaneseWords: ['平均（へいきん）', '平和（へいわ）', '平気だ（へいきだ）', '平日（へいじつ）', '平素（へいそ）', '平方（へいほう）', '平年値（へいねんち）', '平野（へいや）', '太平洋（たいへいよう）'],
    },
    {
      id: 'ing-ming-名',
      rhyme: 'ing',
      pinyin: 'ming',
      kanji: '名',
      onyomi: 'めい',
      japaneseWords: ['有名だ（ゆうめいだ）', '名刺（めいし）', '名所（めいしょ）', '名物（めいぶつ）', '氏名（しめい）', '病名（びょうめい）'],
    },
    {
      id: 'ing-ming-明',
      rhyme: 'ing',
      pinyin: 'ming',
      kanji: '明',
      onyomi: 'めい',
      japaneseWords: ['説明する（せつめいする）', '明治（めいじ）', '発明（はつめい）', '表明する（ひょうめいする）', '文明（ぶんめい）', '明確だ（めいかくだ）', '証明する（しょうめいする）', '説明書（せつめいしょ）', '鮮明だ（せんめいだ）', '不鮮明だ（ふせんめいだ）'],
    },
    {
      id: 'ing-ming-命1',
      rhyme: 'ing',
      pinyin: 'ming',
      kanji: '命',
      onyomi: 'めい',
      japaneseWords: ['生命（せいめい）', '命じる（めいじる）'],
    },
    {
      id: 'ing-ling-零',
      rhyme: 'ing',
      pinyin: 'ling',
      kanji: '零',
      onyomi: 'れい',
      japaneseWords: ['零下（れいか）'],
    },
    {
      id: 'ing-ling-齢',
      rhyme: 'ing',
      pinyin: 'ling',
      kanji: '齢',
      onyomi: 'れい',
      japaneseWords: ['高齢（こうれい）', '年齢（ねんれい）'],
    },
    {
      id: 'ing-jing-京',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '京',
      onyomi: 'きょう',
      japaneseWords: ['京都（きょうと）', '東京（とうきょう）', '京（きょう）', '東京発（とうきょうはつ）'],
    },
    {
      id: 'ing-jing-境',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '境',
      onyomi: 'きょう',
      japaneseWords: ['環境（かんきょう）'],
    },
    {
      id: 'ing-jing-競',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '競',
      onyomi: 'きょう',
      japaneseWords: ['競争（きょうそう）'],
    },
    {
      id: 'ing-xing-興1',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '興',
      onyomi: 'きょう',
      japaneseWords: ['興味（きょうみ）'],
    },
    {
      id: 'ing-xing-行2',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '行',
      onyomi: 'ぎょう',
      japaneseWords: ['行事（ぎょうじ）'],
    },
    {
      id: 'ing-jing-井',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '井',
      onyomi: 'しょう',
      japaneseWords: ['天井（てんじょう）'],
    },
    {
      id: 'ing-qing-情',
      rhyme: 'ing',
      pinyin: 'qing',
      kanji: '情',
      onyomi: 'じょう',
      japaneseWords: ['情報（じょうほう）', '感情（かんじょう）', '友情（ゆうじょう）', '情緒（じょうちょ）', '事情（じじょう）', '苦情（くじょう）', '厚情（こうじょう）', '愛情（あいじょう）'],
    },
    {
      id: 'ing-ding-丁1',
      rhyme: 'ing',
      pinyin: 'ding',
      kanji: '丁',
      onyomi: 'ちょう',
      japaneseWords: ['丁目（ちょうめ）', '丁度（ちょうど）'],
    },
    {
      id: 'ing-ding-頂',
      rhyme: 'ing',
      pinyin: 'ding',
      kanji: '頂',
      onyomi: 'ちょう',
      japaneseWords: ['頂上（ちょうじょう）', '頂戴（ちょうだい）', '登頂（とちょう）'],
    },
    {
      id: 'ing-ting-庁',
      rhyme: 'ing',
      pinyin: 'ting',
      kanji: '庁',
      onyomi: 'ちょう',
      japaneseWords: ['気象庁（きしょうちょう）', '官庁（かんちょう）'],
    },
    {
      id: 'ing-ping-評',
      rhyme: 'ing',
      pinyin: 'ping',
      kanji: '評',
      onyomi: 'ひょう',
      japaneseWords: ['評判（ひょうばん）', '評論（ひょうろん）', '評価する（ひょうかする）'],
    },
    {
      id: 'ing-bing-氷',
      rhyme: 'ing',
      pinyin: 'bing',
      kanji: '氷',
      onyomi: 'ひょう',
      japaneseWords: ['氷河（ひょうが）', '氷山（ひょうざん）'],
    },
    {
      id: 'ing-bing-病',
      rhyme: 'ing',
      pinyin: 'bing',
      kanji: '病',
      onyomi: 'びょう',
      japaneseWords: ['病院（びょういん）', '病気（びょうき）', '病室（びょうしつ）', '病気（生病）（びょうき）', '病名（びょうめい）', '糖尿病（とうにょうびょう）', '心臓病（しんぞうびょう）'],
    },
    {
      id: 'ing-ping-平2',
      rhyme: 'ing',
      pinyin: 'ping',
      kanji: '平',
      onyomi: 'びょう',
      japaneseWords: ['平等（びょうどう）'],
    },
    {
      id: 'ing-ming-命2',
      rhyme: 'ing',
      pinyin: 'ming',
      kanji: '命',
      onyomi: 'みょう',
      japaneseWords: ['寿命（じゅみょう）'],
    },
    {
      id: 'ing-ling-領',
      rhyme: 'ing',
      pinyin: 'ling',
      kanji: '領',
      onyomi: 'りょう',
      japaneseWords: ['要領（ようりょう）'],
    },
    {
      id: 'ing-xing-行1',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '行',
      onyomi: 'こう',
      japaneseWords: ['旅行社（りょこうしゃ）', '銀行（ぎんこう）', '飛行機（ひこうき）', '旅行（りょこう）', '行動（こうどう）', '飛行士（ひこうし）', '流行（りゅうこう）', '親孝行（おやこうこう）', '実行（じっこう）', '決行する（けっこうする）', '飛行場（ひこうじょう）', '通行（つうこう）', '一行（いっこう）'],
    },
    {
      id: 'ing-xing-幸',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '幸',
      onyomi: 'こう',
      japaneseWords: ['幸福（こうふく）'],
    },
    {
      id: 'ing-xing-興2',
      rhyme: 'ing',
      pinyin: 'xing',
      kanji: '興',
      onyomi: 'こう',
      japaneseWords: ['興奮する（こうふんする）'],
    },
    {
      id: 'ing-ying-応',
      rhyme: 'ing',
      pinyin: 'ying',
      kanji: '応',
      onyomi: 'おう',
      japaneseWords: ['応接間（おうせつま）', '対応する（たいおうする）', '応じる（おうじる）', '応用（おうよう）', '一応（いちおう）', '応援する（おうえんする）'],
    },
    {
      id: 'ing-jing-景2',
      rhyme: 'ing',
      pinyin: 'jing',
      kanji: '景',
      onyomi: 'け',
      isSpecial: true,
      japaneseWords: ['景色（けしき）'],
    },
    {
      id: 'ing-ping-瓶',
      rhyme: 'ing',
      pinyin: 'ping',
      kanji: '瓶',
      onyomi: 'びん',
      isSpecial: true,
      japaneseWords: ['花瓶（かびん）', '管瓶（かんびん）'],
    },
  ],
}
