import type { OnyomiRhymeDataset } from '../types'

export const iongDataset: OnyomiRhymeDataset = {
  key: 'iong',
  label: 'iong',
  examples: [
    {
      id: 'iong-xiong-兄',
      rhyme: 'iong',
      pinyin: 'xiong',
      kanji: '兄',
      onyomi: 'きょう',
      japaneseWords: ['兄弟（きょうだい）'],
    },
    {
      id: 'iong-yong-用',
      rhyme: 'iong',
      pinyin: 'yong',
      kanji: '用',
      onyomi: 'よう',
      japaneseWords: [
        '画用紙（がようし）',
        '日用品（にちようひん）',
        '利用する（りようする）',
        '用紙（ようし）',
        '用件（ようけん）',
        '活用する（かつようする）',
        '採用する（さいようする）',
        '用意する（よういする）',
        '御用件（ごようけん）',
        '通用する（つうようする）',
        '実用化（じつようか）',
        '用法（ようほう）',
        '使用する（しようする）',
        '費用（ひよう）',
        '作用（さよう）',
        '応用（おうよう）',
        '慣用句（かんようく）',
        '副作用（ふくさよう）',
      ],
    },
    {
      id: 'iong-xiong-雄',
      rhyme: 'iong',
      pinyin: 'xiong',
      kanji: '雄',
      onyomi: 'ゆう',
      japaneseWords: ['雄大さ（ゆうだいさ）', '雄姿（ゆうし）'],
    },
    {
      id: 'iong-yong-勇',
      rhyme: 'iong',
      pinyin: 'yong',
      kanji: '勇',
      onyomi: 'ゆう',
      japaneseWords: ['勇気（ゆうき）'],
    },
    {
      id: 'iong-yong-永',
      rhyme: 'iong',
      pinyin: 'yong',
      kanji: '永',
      onyomi: 'えい',
      japaneseWords: ['永久に（えいきゅうに）'],
    },
    {
      id: 'iong-yong-泳',
      rhyme: 'iong',
      pinyin: 'yong',
      kanji: '泳',
      onyomi: 'えい',
      japaneseWords: ['水泳（すいえい）'],
    },
  ],
}
