import type { OnyomiRhymeDataset } from '../types'

export const ongDataset: OnyomiRhymeDataset = {
  key: 'ong',
  label: 'ong',
  examples: [
    {
      id: 'ong-gong-工1',
      rhyme: 'ong',
      pinyin: 'gong',
      kanji: '工',
      onyomi: 'こう',
      japaneseWords: ['工場（こうじょう）', '電子工学（でんしこうがく）', '工事（こうじ）', '工業（こうぎょう）', '加工（かこう）', '人工的だ（じんこうてきだ）'],
    },
    {
      id: 'ong-gong-公',
      rhyme: 'ong',
      pinyin: 'gong',
      kanji: '公',
      onyomi: 'こう',
      japaneseWords: ['公園（こうえん）', '公演する（こうえんする）', '公共（こうきょう）', '公社（こうしゃ）'],
    },
    {
      id: 'ong-gong-功',
      rhyme: 'ong',
      pinyin: 'gong',
      kanji: '功',
      onyomi: 'こう',
      japaneseWords: ['成功する（せいこうする）', '専攻（せんこう）'],
    },
    {
      id: 'ong-hong-紅',
      rhyme: 'ong',
      pinyin: 'hong',
      kanji: '紅',
      onyomi: 'こう',
      japaneseWords: ['紅茶（こうちゃ）', '紅葉（こうよう）'],
    },
    {
      id: 'ong-zong-総',
      rhyme: 'ong',
      pinyin: 'zong',
      kanji: '総',
      onyomi: 'そう',
      japaneseWords: ['総人口（そうじんこう）', '国民総生産（こくみんそうせいさん）'],
    },
    {
      id: 'ong-song-送',
      rhyme: 'ong',
      pinyin: 'song',
      kanji: '送',
      onyomi: 'そう',
      japaneseWords: ['送料（そうりょう）', '放送する（ほうそうする）', '運送（うんそう）', '移送する（いそうする）'],
    },
    {
      id: 'ong-dong-東',
      rhyme: 'ong',
      pinyin: 'dong',
      kanji: '東',
      onyomi: 'とう',
      japaneseWords: ['東京（とうきょう）', '東北（とうほく）', '東京発（とうきょうはつ）', '東海道（とうかいどう）', '関東（かんとう）', '東部（とうぶ）'],
    },
    {
      id: 'ong-dong-凍',
      rhyme: 'ong',
      pinyin: 'dong',
      kanji: '凍',
      onyomi: 'とう',
      japaneseWords: ['冷凍（れいとう）', '冷凍庫（れいとうこ）', '凍結する（とうけつする）', '凍傷（とうしょう）'],
    },
    {
      id: 'ong-tong-統',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '統',
      onyomi: 'とう',
      japaneseWords: ['伝統（でんとう）', '統計（とうけい）', '伝統的だ（でんとうてきだ）'],
    },
    {
      id: 'ong-tong-筒',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '筒',
      onyomi: 'とう',
      japaneseWords: ['封筒（ふうとう）'],
    },
    {
      id: 'ong-tong-同',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '同',
      onyomi: 'どう',
      japaneseWords: ['共同（きょうどう）', '同世代（どうせだい）', '同時（どうじ）', '同量（どうりょう）', '同封（どうふう）', '一同（いちどう）', '共同体（きょうどうたい）'],
    },
    {
      id: 'ong-tong-銅',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '銅',
      onyomi: 'どう',
      japaneseWords: ['銅（どう）', '銅貨（どうか）'],
    },
    {
      id: 'ong-dong-洞',
      rhyme: 'ong',
      pinyin: 'dong',
      kanji: '洞',
      onyomi: 'どう',
      japaneseWords: ['雪洞（せつどう）'],
    },
    {
      id: 'ong-dong-動',
      rhyme: 'ong',
      pinyin: 'dong',
      kanji: '動',
      onyomi: 'どう',
      japaneseWords: ['動物園（どうぶつえん）', '自動（じどう）', '感動する（かんどうする）', '移動する（いどうする）', '運動（うんどう）', '動物（どうぶつ）', '運動会（うんどうかい）', '自動的だ（じどうてきだ）', '行動（こうどう）', '活動（かつどう）', '原動力（げんどうりょく）', '小動物（しょうどうぶつ）', '不動産（ふどうさん）', '変動する（へんどうする）', '出動する（しゅつどうする）'],
    },
    {
      id: 'ong-dong-働',
      rhyme: 'ong',
      pinyin: 'dong',
      kanji: '働',
      onyomi: 'どう',
      japaneseWords: ['労働（ろうどう）'],
    },
    {
      id: 'ong-nong-農',
      rhyme: 'ong',
      pinyin: 'nong',
      kanji: '農',
      onyomi: 'のう',
      japaneseWords: ['農業（のうぎょう）', '農作物（のうさくぶつ）', '農家（のうか）', '農作業（のうさぎょう）', '農村（のうそん）', '農民（のうみん）'],
    },
    {
      id: 'ong-nong-濃',
      rhyme: 'ong',
      pinyin: 'nong',
      kanji: '濃',
      onyomi: 'のう',
      japaneseWords: ['濃緑（のうりょく）'],
    },
    {
      id: 'ong-zhong-終',
      rhyme: 'ong',
      pinyin: 'zhong',
      kanji: '終',
      onyomi: 'しゅう',
      japaneseWords: ['終業（しゅうぎょう）'],
    },
    {
      id: 'ong-chong-充',
      rhyme: 'ong',
      pinyin: 'chong',
      kanji: '充',
      onyomi: 'じゅう',
      japaneseWords: ['充実（じゅうじつ）'],
    },
    {
      id: 'ong-zhong-重',
      rhyme: 'ong',
      pinyin: 'zhong',
      kanji: '重',
      onyomi: 'じゅう',
      japaneseWords: ['体重（たいじゅう）', '重傷（じゅうしょう）'],
    },
    {
      id: 'ong-chong-虫',
      rhyme: 'ong',
      pinyin: 'chong',
      kanji: '虫',
      onyomi: 'ちゅう',
      japaneseWords: ['昆虫（こんちゅう）'],
    },
    {
      id: 'ong-zhong-中',
      rhyme: 'ong',
      pinyin: 'zhong',
      kanji: '中',
      onyomi: 'ちゅう',
      japaneseWords: ['中国（ちゅうごく）', '中華料理（ちゅうかりょうり）', '中日（ちゅうにち）', '途中（とちゅう）', '中止（ちゅうし）', '中心（ちゅうしん）', '中旬（ちゅうじゅん）', '中腹（ちゅうふく）', '中間（ちゅうかん）', '中学校（ちゅうがっこう）', '的中する（てきちゅうする）', '訪問中（ほうもんちゅう）', 'お中元（おちゅうげん）', '集中する（しゅうちゅうする）', '空中（くうちゅう）', '最中（さいちゅう）'],
    },
    {
      id: 'ong-zhong-忠',
      rhyme: 'ong',
      pinyin: 'zhong',
      kanji: '忠',
      onyomi: 'ちゅう',
      japaneseWords: ['忠告（ちゅうこく）'],
    },
    {
      id: 'ong-rong-融',
      rhyme: 'ong',
      pinyin: 'rong',
      kanji: '融',
      onyomi: 'ゆう',
      japaneseWords: ['融合（ゆうごう）'],
    },
    {
      id: 'ong-rong-容',
      rhyme: 'ong',
      pinyin: 'rong',
      kanji: '容',
      onyomi: 'よう',
      japaneseWords: ['内容（ないよう）', '美容院（びよういん）', '容赦（ようしゃ）'],
    },
    {
      id: 'ong-rong-溶',
      rhyme: 'ong',
      pinyin: 'rong',
      kanji: '溶',
      onyomi: 'よう',
      japaneseWords: ['溶接（ようせつ）', '溶岩（ようがん）'],
    },
    {
      id: 'ong-rong-冗',
      rhyme: 'ong',
      pinyin: 'rong',
      kanji: '冗',
      onyomi: 'じょう',
      japaneseWords: ['冗談（じょうだん）'],
    },
    {
      id: 'ong-gong-共',
      rhyme: 'ong',
      pinyin: 'gong',
      kanji: '共',
      onyomi: 'きょう',
      isSpecial: true,
      japaneseWords: ['共同（きょうどう）', '公共（こうきょう）', '共通語（きょうつうご）', '共同体（きょうどうたい）', '共通する（きょうつうする）'],
    },
    {
      id: 'ong-zong-宗',
      rhyme: 'ong',
      pinyin: 'zong',
      kanji: '宗',
      onyomi: 'しゅう',
      isSpecial: true,
      japaneseWords: ['宗教（しゅうきょう）', '宗教的だ（しゅうきょうてきだ）'],
    },
    {
      id: 'ong-cong-従',
      rhyme: 'ong',
      pinyin: 'cong',
      kanji: '従',
      onyomi: 'じゅう',
      isSpecial: true,
      japaneseWords: ['従来（じゅうらい）'],
    },
    {
      id: 'ong-zong-縦',
      rhyme: 'ong',
      pinyin: 'zong',
      kanji: '縦',
      onyomi: 'じゅう',
      isSpecial: true,
      japaneseWords: ['操縦する（そうじゅうする）'],
    },
    {
      id: 'ong-zhong-種',
      rhyme: 'ong',
      pinyin: 'zhong',
      kanji: '種',
      onyomi: 'しゅ',
      isSpecial: true,
      japaneseWords: ['種類（しゅるい）', '品種（ひんしゅ）', '多種多様（たしゅたよう）', '一種（いっしゅ）', '二種（にしゅ）'],
    },
    {
      id: 'ong-kong-空',
      rhyme: 'ong',
      pinyin: 'kong',
      kanji: '空',
      onyomi: 'くう',
      isSpecial: true,
      japaneseWords: ['航空便（こうくうびん）', '空港（くうこう）', '空欄（くうらん）', '航空（こうくう）', '真空管（しんくうかん）', '空気（くうき）', '空中（くうちゅう）'],
    },
    {
      id: 'ong-tong-通',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '通',
      onyomi: 'つう',
      isSpecial: true,
      japaneseWords: ['通信（つうしん）', '普通（ふつう）', '交通（こうつう）', '通用する（つうようする）', '通訳（つうやく）', '通学する（つうがくする）', '共通語（きょうつうご）', '交通量（こうつうりょう）', '通知（つうち）', '通勤する（つうきんする）', '通行（つうこう）', '二通（につう）', '流通（りゅうつう）', '共通する（きょうつうする）'],
    },
    {
      id: 'ong-tong-痛',
      rhyme: 'ong',
      pinyin: 'tong',
      kanji: '痛',
      onyomi: 'つう',
      isSpecial: true,
      japaneseWords: ['頭痛（ずつう）', '苦痛（くつう）'],
    },
    {
      id: 'ong-rong-栄',
      rhyme: 'ong',
      pinyin: 'rong',
      kanji: '栄',
      onyomi: 'えい',
      isSpecial: true,
      japaneseWords: ['栄養（えいよう）', '栄養分（えいようぶん）', '清栄（せいえい）', '繁栄（はんえい）'],
    },
    {
      id: 'ong-gong-工2',
      rhyme: 'ong',
      pinyin: 'gong',
      kanji: '工',
      onyomi: 'く',
      isSpecial: true,
      japaneseWords: ['工夫する（くふうする）'],
    },
  ],
}
