import type { OnyomiRhymeDataset } from '../types'

export const uangDataset: OnyomiRhymeDataset = {
  key: 'uang',
  label: 'uang',
  examples: [
    {
      id: 'uang-guang-光',
      rhyme: 'uang',
      pinyin: 'guang',
      kanji: '光',
      onyomi: 'こう',
      japaneseWords: ['観光（かんこう）', '光景（こうけい）', '観光客（かんこうきゃく）', '脚光（きゃっこう）'],
    },
    {
      id: 'uang-guang-広',
      rhyme: 'uang',
      pinyin: 'guang',
      kanji: '広',
      onyomi: 'こう',
      japaneseWords: ['広告（こうこく）', '広大だ（こうだい）'],
    },
    {
      id: 'uang-huang-黄',
      rhyme: 'uang',
      pinyin: 'huang',
      kanji: '黄',
      onyomi: 'こう',
      japaneseWords: ['黄河（こうが）'],
    },
    {
      id: 'uang-zhuang-装',
      rhyme: 'uang',
      pinyin: 'zhuang',
      kanji: '装',
      onyomi: 'そう',
      japaneseWords: ['塗装（とそう）', '洋装店（ようそうてん）', '服装（ふくそう）', '内装（ないそう）'],
    },
    {
      id: 'uang-wang-王',
      rhyme: 'uang',
      pinyin: 'wang',
      kanji: '王',
      onyomi: 'おう',
      japaneseWords: ['王（おう）'],
    },
    {
      id: 'uang-wang-往',
      rhyme: 'uang',
      pinyin: 'wang',
      kanji: '往',
      onyomi: 'おう',
      japaneseWords: ['往復する（おうふくする）'],
    },
    {
      id: 'uang-wang-亡',
      rhyme: 'uang',
      pinyin: 'wang',
      kanji: '亡',
      onyomi: 'ぼう',
      japaneseWords: ['死亡（しぼう）'],
    },
    {
      id: 'uang-wang-望',
      rhyme: 'uang',
      pinyin: 'wang',
      kanji: '望',
      onyomi: 'ぼう',
      japaneseWords: ['希望する（きぼうする）', '志望する（しぼうする）'],
    },
    {
      id: 'uang-kuang-狂',
      rhyme: 'uang',
      pinyin: 'kuang',
      kanji: '狂',
      onyomi: 'きょう',
      japaneseWords: ['狂言（きょうげん）'],
    },
    {
      id: 'uang-kuang-況',
      rhyme: 'uang',
      pinyin: 'kuang',
      kanji: '況',
      onyomi: 'きょう',
      japaneseWords: ['状況（じょうきょう）'],
    },
    {
      id: 'uang-zhuang-状',
      rhyme: 'uang',
      pinyin: 'zhuang',
      kanji: '状',
      onyomi: 'じょう',
      japaneseWords: ['状況（じょうきょう）', '年賀状（ねんがじょう）', '状態（じょうたい）', '案内状（あんないじょう）'],
    },
  ],
}
