export const onyomiOrderWithCounts = [
  { onyomi: 'こう', count: 20 },
  { onyomi: 'しょう', count: 20 },
  { onyomi: 'じょう', count: 12 },
  { onyomi: 'せい', count: 12 },
  { onyomi: 'きょう', count: 11 },
  { onyomi: 'ちょう', count: 8 },
  { onyomi: 'とう', count: 8 },
  { onyomi: 'よう', count: 8 },
  { onyomi: 'えい', count: 7 },
  { onyomi: 'けい', count: 7 },
  { onyomi: 'そう', count: 7 },
  { onyomi: 'どう', count: 7 },
  { onyomi: 'ぼう', count: 7 },
  { onyomi: 'ほう', count: 6 },
  { onyomi: 'ぞう', count: 5 },
  { onyomi: 'てい', count: 5 },
  { onyomi: 'りょう', count: 5 },
  { onyomi: 'じゅう', count: 4 },
  { onyomi: 'おう', count: 3 },
  { onyomi: 'ちゅう', count: 3 },
  { onyomi: 'のう', count: 3 },
  { onyomi: 'めい', count: 3 },
  { onyomi: 'ゆう', count: 3 },
  { onyomi: 'れい', count: 3 },
  { onyomi: 'しゅう', count: 2 },
  { onyomi: 'つう', count: 2 },
  { onyomi: 'ひょう', count: 2 },
  { onyomi: 'びょう', count: 2 },
  { onyomi: 'ふう', count: 2 },
  { onyomi: 'ぎょう', count: 1 },
  { onyomi: 'く', count: 1 },
  { onyomi: 'くう', count: 1 },
  { onyomi: 'け', count: 1 },
  { onyomi: 'げい', count: 1 },
  { onyomi: 'ごう', count: 1 },
  { onyomi: 'しゅ', count: 1 },
  { onyomi: 'と', count: 1 },
  { onyomi: 'ねい', count: 1 },
  { onyomi: 'びん', count: 1 },
  { onyomi: 'ふ', count: 1 },
  { onyomi: 'へい', count: 1 },
  { onyomi: 'みょう', count: 1 },
  { onyomi: 'ろう', count: 1 },
] as const

export const onyomiOrder = onyomiOrderWithCounts.map((item) => item.onyomi)

export type OnyomiKey = (typeof onyomiOrder)[number]
